fest: support coroutine socket writev
swoole/swoole-src pull request #3764
Opened 2020-10-23 05:13 UTC by huanghantao

```php
/**
 * @param string[] $iov
 */
Coroutine::Socket::writev(array $iov, $timeout);
```

2020-10-25 07:55 UTC, twose requested changes

2020-10-25 07:55 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +    iovec iov[iovcnt];
理论上有爆栈风险

2020-10-25 07:55 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +    iov_len = Z_LVAL(Z_ARRVAL_P(element)->arData[0].val);
传入非int类型会内存错误, 要么检测类型, 要么用zval_get_long

2020-10-25 07:55 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +        for (size_t i = 0; i < iovcnt; i++) {
应该也可以while (iovcnt--)

2020-10-25 07:55 UTC, twose commented on src/coroutine/socket.cc
> +        retval = socket->writev(iov, iovcnt);
没这么简单的, 写入量大的时候, 每次writev可能只写入了部分数据, 下次写入时相当于断点续传, 需要重新计算并构造新的iov

2020-10-25 07:55 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +    add_next_index_str(element, iov_base);
如果失败了, 是否需要删除这个元素? 如果不删除, 那么就不能再复用这个数组
此外, 我怀疑这个写法是不安全的, 数组里的元素引用计数若不为1, 插入时违反了写时拷贝原则, 此外, 它也有可能会是不可变数组

2020-10-25 07:56 UTC, twose requested changes

2020-10-25 07:56 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +    iovec iov[iovcnt];
理论上有爆栈风险

2020-10-25 07:56 UTC, twose commented on src/coroutine/socket.cc
> +        retval = socket->readv(iov, iovcnt);
同writev, readv也可能每次都读到了部分数据, 下次读取需要从新的位置开始

2020-10-30 14:50 UTC, matyhtf commented on include/swoole_util.h
> +static inline int get_iovector_index(const struct iovec *iov, int iovcnt, size_t __n, int &index, size_t &offset_bytes) {
这个函数只有 readv, writev 会用，不如直接放到 network/socket.cc 中，放到这里没有复用的价值，还导致 swoole_util.h 依赖了一个 sys/uio.h

2020-10-30 15:04 UTC, matyhtf commented on ext-src/php_swoole_cxx.h
> +    inline static zend_string *fetch_zend_string_by_val(char *val) {
这个函数，我觉得可以直接放到 zend 命名空间里面，和 zend::String 的关系并不大的

2020-10-30 15:08 UTC, matyhtf commented on src/coroutine/socket.cc
> +    do
循环发送可以移动到 wait_event 的 writable_callback 里面，否则底层还是会多次唤醒协程的

2020-10-30 18:00 UTC, twose requested changes

2020-10-30 18:03 UTC, twose commented
有一个非常大的问题, 原始的socket读写我们是不暴露给PHP层的, 比如Socket::read()和Socket::write(), 更重要的是readv和writev无法支持SSL连接, 那么它将是一个有缺陷的功能(你无法写出通用的代码), 解决起来会比现在复杂, 如nginx中writev会通过一块16k的buffer进行发送(因为单个SSL报文最大16k), 又或是借助BIO解决

2020-11-01 05:15 UTC, matyhtf commented on ext-src/swoole_socket_coro.cc
> +    ZEND_ARG_INFO(0, iov)
单数是对的，vector 本身就是容器的意思，vectors 表示多个容器，这里实际上只有一个容器。

2020-11-01 09:15 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +    ZEND_ARG_INFO(0, iov)
Linux文档，iovcnt指the vector count, 也就是多个

2020-11-01 09:19 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +    ZEND_ARG_INFO(0, iov)
哈哈，是英语问题，vector单复同形

2020-11-01 09:35 UTC, twose commented on ext-src/swoole_socket_coro.cc
> +    ZEND_ARG_INFO(0, iov)
确实

2020-11-05 15:13 UTC, merged