Support curl-native hook
swoole/swoole-src pull request #3863
Opened 2020-11-20 11:42 UTC by matyhtf

2020-11-20 13:03 UTC, twose requested changes

2020-11-20 13:03 UTC, twose commented on ext-src/swoole_runtime.cc
> +        flags ^= PHPCoroutine::HOOK_CURL;
应该是 `flags &= ~PHPCoroutine::HOOK_CURL;`?
检测到同时有两个flag应该予以报错
`if ((flags & (PHPCoroutine::HOOK_CURL | PHPCoroutine::HOOK_NATIVE_CURL)) == (PHPCoroutine::HOOK_CURL | PHPCoroutine::HOOK_NATIVE_CURL))`

2020-11-20 13:03 UTC, twose commented on ext-src/php_swoole_coroutine.h
> +        HOOK_ALL               = 0x7fffffff ^ HOOK_NATIVE_CURL,
如果评估可以得出native更优, 是否可以在有native支持时默认为native模式

2020-11-20 13:03 UTC, twose commented
是否可以将原先的单测套上循环, 在native模式下再测一次

2020-11-20 14:41 UTC, matyhtf commented on ext-src/php_swoole.h
> +static sw_inline zend_bool ZVAL_IS_TRUE(zval *v)
zval_is_true 会进行类型转换，这里只是为了判断 Z_TYPE_P(v) 是否为 IS_TRUE

2020-11-21 16:41 UTC, matyhtf commented on ext-src/php_swoole_coroutine.h
> +        HOOK_ALL               = 0x7fffffff ^ HOOK_NATIVE_CURL,
等过几个版本后，替换底层实现。

2020-11-24 02:10 UTC, matyhtf commented
> 是否可以将原先的单测套上循环, 在native模式下再测一次

不需要，native curl client ，大部分逻辑是 curl 完成的，这里的单测应该重新写，覆盖到 `interface.cc` 本身的关键逻辑。

2020-11-28 10:44 UTC, merged