Stubs for swoole
swoole/swoole-src pull request #4497
Opened 2021-11-17 10:46 UTC by NathanFreeman

swoole_timer ✔️

swoole_table ✔️

swoole_lock ✔️

swoole_event ✔️

swoole_atomic ✔️

swoole_runtime ✔️

swoole_websocket ✔️

swoole_channel_coro ✔️

swoole_client_sync ✔️

swoole_http_request ✔️

swoole_http_response ✔️

swoole_admin_server ✔️

php_swoole_function ✔️

swoole_name_resolver ✔️

2021-11-18 13:18 UTC, NathanFreeman commented
We need to review the changes to swoole_server again even thought all checks hava passed.
swoole_server is a very important module.

2021-11-19 12:11 UTC, matyhtf commented
> We need to review the changes to swoole_server again even thought all checks have passed. swoole_server is a very important module.

我來 review 這部分代碼

2021-11-19 12:14 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function on(mixed $event_name, mixed $callback): bool {}
event_name 是字符串，callback 應該是 callable

2021-11-19 12:32 UTC, matyhtf requested changes

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function getCallback(mixed $event_name): Closure|string|null|array {}
event_name 是字符串

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function listen(string $host, int $port, int $sock_type = SWOOLE_SOCK_TCP): bool|Server\Port {}
第三个参数没有默认值，必须要填写

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function taskWaitMulti(mixed $tasks, float $timeout = 0.5): bool|array {}
第一个参数 tasks 必须为数组

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function taskCo(mixed $tasks, float $timeout = 0.5): array {}
tasks 必须为数组

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function rewind(): void {}
需要与 zend_ce_iterator 接口保持一致

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function pack(mixed $data): string|bool {}
多了一个，pack 只有静态方法

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_http_request.stub.php
> +		public function create(array $options = []): Request|bool {}
多了一个 create 方法

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_http_response.stub.php
> +		public function create(mixed $server = -1, int $fd = -1): Response|bool {}
create 是静态方法

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_runtime.stub.php
> +		public function enableCoroutine(bool $enable = true, int $flags = SWOOLE_HOOK_ALL): bool {}
都是静态方法，没有动态

2021-11-19 12:32 UTC, matyhtf commented on stubs/php_swoole_websocket.stub.php
> +		public function pack(string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string {}
pack 和 unpack 是静态方法

2021-11-20 02:22 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function on(mixed $event_name, mixed $callback): bool {}
已经修改好了，谢谢。

2021-11-20 02:22 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function getCallback(mixed $event_name): Closure|string|null|array {}
OK

2021-11-20 02:23 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function listen(string $host, int $port, int $sock_type = SWOOLE_SOCK_TCP): bool|Server\Port {}
文档上面的$sock_type写着有默认值😂

2021-11-20 02:39 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function taskWaitMulti(mixed $tasks, float $timeout = 0.5): bool|array {}
已修复，谢谢

2021-11-20 02:39 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function taskCo(mixed $tasks, float $timeout = 0.5): array {}
已修复，谢谢

2021-11-20 02:44 UTC, NathanFreeman commented on stubs/php_swoole_http_request.stub.php
> +		public function create(array $options = []): Request|bool {}
swoole_http_request.cc有一个create方法，我已经改成静态方法了。

2021-11-20 02:44 UTC, NathanFreeman commented on stubs/php_swoole_http_response.stub.php
> +		public function create(mixed $server = -1, int $fd = -1): Response|bool {}
已修改，谢谢。

2021-11-20 02:45 UTC, NathanFreeman commented on stubs/php_swoole_runtime.stub.php
> +		public function enableCoroutine(bool $enable = true, int $flags = SWOOLE_HOOK_ALL): bool {}
已修改，谢谢。

2021-11-20 02:45 UTC, NathanFreeman commented on stubs/php_swoole_websocket.stub.php
> +		public function pack(string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string {}
已修改，谢谢。

2021-11-20 02:45 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function pack(mixed $data): string|bool {}
已处理，谢谢。

2021-11-20 06:18 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function on(mixed $event_name, mixed $callback): bool {}
https://wiki.swoole.com/#/server/methods?id=on
这个$callback可以是字符串，对象数组等。

2021-11-20 06:29 UTC, NathanFreeman commented on stubs/php_swoole_server.stub.php
> +        public function rewind(): void {}
swoole_server实现了Iterator的构造和析构函数

2021-11-23 05:25 UTC, matyhtf commented on stubs/php_swoole_ex.stub.php
> +function swoole_get_objects(): bool|array
与 admin_server 重复了

2021-11-23 05:25 UTC, matyhtf commented on stubs/php_swoole_http2_client_coro.stub.php
> +        public function read(): \Swoole\Http2\Response|bool {}
read 第一个参数是 timeout

2021-11-23 05:25 UTC, matyhtf commented on stubs/php_swoole_http_client_coro.stub.php
> +		public function __construct(string $host, int $port, bool $ssl = false) {}
port 是可选参数，默认为 0

2021-11-23 05:25 UTC, matyhtf commented on stubs/php_swoole_server.stub.php
> +        public function listen(string $host, int $port, int $sock_type = SWOOLE_SOCK_TCP): bool|Server\Port {}
稍后改一下文档

2021-11-23 13:29 UTC, NathanFreeman commented on stubs/php_swoole.stub.php
> +function swoole_async_dns_lookup_coro(mixed $domain_name, float $timeout = 60, int $type = AF_INET): bool
已改，谢谢。

2021-11-23 13:29 UTC, NathanFreeman commented on stubs/php_swoole.stub.php
> +function swoole_coroutine_defer(callable $callback): ?bool
```c++
PHP_FUNCTION(swoole_coroutine_defer) {
    zend_fcall_info fci;
    zend_fcall_info_cache fci_cache;
    zend::Function *defer_fci;

    ZEND_PARSE_PARAMETERS_START(1, 1)
    Z_PARAM_FUNC(fci, fci_cache)
    ZEND_PARSE_PARAMETERS_END_EX(RETURN_FALSE);
```

他这里有一个RETURN_FALSE

2021-11-24 01:00 UTC, matyhtf requested changes

2021-11-24 01:00 UTC, matyhtf commented on stubs/php_swoole_websocket.stub.php
> +		public static function pack(string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string {}
pack 和 unpack 是 WebSocket\Server::pack()/unpack() 的别名，参数是一致的

2021-11-25 08:39 UTC, NathanFreeman commented on stubs/php_swoole.stub.php
> +function swoole_coroutine_defer(callable $callback): ?bool
已改，谢谢

2021-11-25 08:39 UTC, NathanFreeman commented on stubs/php_swoole_atomic.stub.php
> +        public function set(int $value): ?bool {}
已修改

2021-11-25 08:40 UTC, NathanFreeman commented on stubs/php_swoole_atomic.stub.php
> +        public function add(int $add_value = 1): int|bool {}
已修改
```c++
namespace Swoole\Atomic {
    class Long {
        public function __construct(int $value = 0) {}
        public function add(int $add_value = 1): int {}
        public function sub(int $sub_value = 1): int {}
        public function get(): int {}
        public function set(int $value): void {}
        public function cmpset(int $cmp_value, int $new_value): bool {}
    }
}
```

2021-11-25 08:40 UTC, NathanFreeman commented on stubs/php_swoole_client.stub.php
> +		public function __construct(int $type, int $async = SWOOLE_SOCK_SYNC, string $id = '') {}
已修改
```php
namespace Swoole {
	class Client {
		public function __construct(int $type, bool $async = SWOOLE_SOCK_SYNC, string $id = '') {}
```

2021-11-25 08:44 UTC, NathanFreeman commented on stubs/php_swoole_client.stub.php
> +		public function connect(string $host, int $port, float $timeout = 0.5, int $sock_flag = 0): bool {}
已修改
```php
public function connect(string $host, int $port = 0, float $timeout = 0.5, int $sock_flag = 0): bool {}
```

2021-11-25 08:49 UTC, NathanFreeman commented on stubs/php_swoole_ex.stub.php
> +function swoole_get_objects(): bool|array
已经删除php_swoole_admin_server.stub.php

2021-11-25 08:56 UTC, NathanFreeman commented on stubs/php_swoole_http2_client_coro.stub.php
> +        public function read(): \Swoole\Http2\Response|bool {}
已修复
```php
        public function recv(float $timeout = 0): \Swoole\Http2\Response|false {}
        public function read(float $timeout = 0): \Swoole\Http2\Response|false {}
```

2021-11-25 08:56 UTC, NathanFreeman commented on stubs/php_swoole_http_client_coro.stub.php
> +		public function __construct(string $host, int $port, bool $ssl = false) {}
已修改
```php
public function __construct(string $host, int $port = 0, bool $ssl = false) {}
```

2021-11-25 08:58 UTC, NathanFreeman commented on stubs/php_swoole_websocket.stub.php
> +		public function push(int $fd, string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): bool {}
已修改
```php
public function push(int $fd, \Swoole\WebSocket\Frame|string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): bool {}
```

2021-11-25 08:58 UTC, NathanFreeman commented on stubs/php_swoole_websocket.stub.php
> +		public static function pack(string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string {}
已修改
```php
public static function pack(\Swoole\WebSocket\Frame|string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string {}
public static function unpack(string $data): \Swoole\WebSocket\Frame|false {}
```

2021-11-25 08:59 UTC, NathanFreeman commented on stubs/php_swoole_websocket.stub.php
> +		public static function pack(string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string {}
已修改
```php
public static function pack(\Swoole\WebSocket\Frame|string $data, int $opcode = WEBSOCKET_OPCODE_TEXT, int $flags = SWOOLE_WEBSOCKET_FLAG_FIN): string {}
public static function unpack(string $data): \Swoole\WebSocket\Frame|false {}
```

2021-11-26 08:02 UTC, merged