Time consuming calculation of coroutines.
swoole/swoole-src pull request #4516
Opened 2021-11-29 14:30 UTC by NathanFreeman

2021-12-01 11:46 UTC, matyhtf approved these changes

2021-12-01 14:42 UTC, matyhtf commented on tests/swoole_coroutine/execute_time.phpt
> +    go(function(){
run 中已创建协程，不需要再使用 go 创建新协程

2021-12-01 14:42 UTC, matyhtf commented on tests/swoole_coroutine/execute_time.phpt
> +        Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL);
- 建议增加 CPU 时间的测试，可以加一个大的 for 循环或者其他计算逻辑
- 可以并发测试，创建多个协程，观察每个协程的执行时间和总的执行时间，以及协程的流逝时间

2021-12-04 02:33 UTC, NathanFreeman commented on tests/swoole_coroutine/execute_time.phpt
> +    go(function(){
OK

2021-12-04 02:33 UTC, NathanFreeman commented on tests/swoole_coroutine/execute_time.phpt
> +        Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL);
已修改单元测试

2021-12-08 02:31 UTC, twose requested changes

2021-12-08 02:31 UTC, twose commented on include/swoole_coroutine.h
> +            resume_coroutine->switch_msec = Timer::get_absolute_msec();
存一下Timer::get_absolute_msec()到栈变量上省得调两次

2021-12-09 02:25 UTC, matyhtf requested changes

2021-12-09 02:25 UTC, matyhtf commented on src/coroutine/base.cc
> +    Coroutine::calc_execute_msec(origin, this);
在 `Coroutine` 类中，`calc_execute_msec` 前面不需要加类名

2021-12-09 02:25 UTC, matyhtf commented on include/swoole_coroutine.h
> +    long switch_msec = time<seconds_type>(true);
应该是 usec

2021-12-10 05:47 UTC, merged