Replacing php_swoole_fatal_error by zend_throw_exception in __construct function.
swoole/swoole-src pull request #4528
Opened 2021-12-06 14:50 UTC by NathanFreeman

2021-12-07 01:37 UTC, twose requested changes

2021-12-07 01:37 UTC, twose commented on ext-src/swoole_client.cc
> +        zend_throw_exception(swoole_exception_ce, "please install the ext-async extension, using Swoole\\Async\\Client", SW_ERROR_PHP_FATAL_ERROR);
这些代码原本都是不会继续往下运行的，改成exception以后都变成会继续运行了，有一些可能还涉及到资源释放，因为不是fatal error了

2021-12-07 01:46 UTC, NathanFreeman commented on ext-src/swoole_client.cc
> +        zend_throw_exception(swoole_exception_ce, "please install the ext-async extension, using Swoole\\Async\\Client", SW_ERROR_PHP_FATAL_ERROR);
那我在zend_throw_exception之后加上return，结束函数的运行可以吗

2021-12-07 02:26 UTC, matyhtf commented on ext-src/swoole_client.cc
> +        zend_throw_exception(swoole_exception_ce, "please install the ext-async extension, using Swoole\\Async\\Client", SW_ERROR_PHP_FATAL_ERROR);
这里需要 RETURN_FALSE

2021-12-07 02:27 UTC, matyhtf requested changes

2021-12-07 02:27 UTC, matyhtf commented on ext-src/swoole_client_coro.cc
> +        zend_throw_exception_ex(swoole_exception_ce, SW_ERROR_PHP_FATAL_ERROR, "Constructor of %s can only be called once", SW_Z_OBJCE_NAME_VAL_P(ZEND_THIS));
需要添加 RETURN_FALSE;

2021-12-07 02:27 UTC, twose commented on ext-src/swoole_client.cc
> +        zend_throw_exception(swoole_exception_ce, "please install the ext-async extension, using Swoole\\Async\\Client", SW_ERROR_PHP_FATAL_ERROR);
RETURN_THROWS()，异常抛出时函数没有返回值
还需要检查前面有没有资源没释放，因为进程会继续运行，包括资源可能会进入不可复用状态

2021-12-16 01:59 UTC, matyhtf commented on ext-src/swoole_client.cc
> +        zend_throw_exception(swoole_exception_ce, "please install the ext-async extension, using Swoole\\Async\\Client", SW_ERROR_PHP_FATAL_ERROR);
RETURN_THROWS 是 8.0 加入的，需要考慮向前兼容性，需使用 RETURN_FALSE

2021-12-16 01:59 UTC, merged